const h1=document.createElement("h1");
h1.innerText="Calculator";
document.querySelector("body").appendChild(h1);
const div1=document.createElement("div");
div1.classList.add("container");
document.querySelector("body").appendChild(div1);
const br=document.createElement("br");
div1.appendChild(br);
const br1=document.createElement("br");
div1.appendChild(br1);
const form=document.createElement("form");
div1.appendChild(form);
const input=document.createElement("input");
input.setAttribute("type","text");
input.setAttribute("name","main");
form.appendChild(input);
const br2=document.createElement("br");
form.appendChild(br2);
const br3=document.createElement("br");
form.appendChild(br3);
const table=document.createElement("table");
table.setAttribute("style","width:0; height:0px");
form.appendChild(table);
const tr1=document.createElement("tr");
table.appendChild(tr1);
const td1=document.createElement("td");
tr1.appendChild(td1);
const input1=document.createElement("input");
input1.setAttribute("type","button");
input1.setAttribute("value","+");
input1.setAttribute("onclick","main.value+='+'");
td1.appendChild(input1);
const td2=document.createElement("td");
tr1.appendChild(td2);
const input2=document.createElement("input");
input2.setAttribute("type","button");
input2.setAttribute("value","-");
input2.setAttribute("onclick","main.value+='-'");
td2.appendChild(input2);
const td3=document.createElement("td");
tr1.appendChild(td3);
const input3=document.createElement("input");
input3.setAttribute("type","button");
input3.setAttribute("value","*");
input3.setAttribute("onclick","main.value+='*'");
td3.appendChild(input3);
const td4=document.createElement("td");
tr1.appendChild(td4);
const input4=document.createElement("input");
input4.setAttribute("type","button");
input4.setAttribute("value","/");
input4.setAttribute("onclick","main.value+='/'");
td4.appendChild(input4);
const tr2=document.createElement("tr");
table.appendChild(tr2);
const td5=document.createElement("td");
tr2.appendChild(td5);
const input5=document.createElement("input");
input5.setAttribute("type","button");
input5.setAttribute("value","1");
input5.setAttribute("onclick","main.value+='1'");
td5.appendChild(input5);
const td6=document.createElement("td");
tr2.appendChild(td6);
const input6=document.createElement("input");
input6.setAttribute("type","button");
input6.setAttribute("value","2");
input6.setAttribute("onclick","main.value+='2'");
td6.appendChild(input6);
const td7=document.createElement("td");
tr2.appendChild(td7);
const input7=document.createElement("input");
input7.setAttribute("type","button");
input7.setAttribute("value","3");
input7.setAttribute("onclick","main.value+='3'");
td7.appendChild(input7);
const td8=document.createElement("td");
tr2.appendChild(td8);
const input8=document.createElement("input");
input8.setAttribute("type","button");
input8.setAttribute("value","4");
input8.setAttribute("onclick","main.value+='4'");
td8.appendChild(input8);
const tr3=document.createElement("tr");
table.appendChild(tr3);
const td9=document.createElement("td");
tr3.appendChild(td9);
const input9=document.createElement("input");
input9.setAttribute("type","button");
input9.setAttribute("value","5");
input9.setAttribute("onclick","main.value+='5'");
td9.appendChild(input9);
const td10=document.createElement("td");
tr3.appendChild(td10);
const input10=document.createElement("input");
input10.setAttribute("type","button");
input10.setAttribute("value","6");
input10.setAttribute("onclick","main.value+='6'");
td10.appendChild(input10);
const td11=document.createElement("td");
tr3.appendChild(td11);
const input11=document.createElement("input");
input11.setAttribute("type","button");
input11.setAttribute("value","7");
input11.setAttribute("onclick","main.value+='7'");
td11.appendChild(input11);
const td12=document.createElement("td");
tr3.appendChild(td12);
const input12=document.createElement("input");
input12.setAttribute("type","button");
input12.setAttribute("value","8");
input12.setAttribute("onclick","main.value+='8'");
td12.appendChild(input12);
const tr4=document.createElement("tr");
table.appendChild(tr4);
const td13=document.createElement("td");
tr4.appendChild(td13);
const input13=document.createElement("input");
input13.setAttribute("type","button");
input13.setAttribute("value","9");
input13.setAttribute("onclick","main.value+='9'");
td13.appendChild(input13);
const td14=document.createElement("td");
tr4.appendChild(td14);
const input14=document.createElement("input");
input14.setAttribute("type","button");
input14.setAttribute("value","0");
input14.setAttribute("onclick","main.value+='0'");
td14.appendChild(input14);
const td15=document.createElement("td");
tr4.appendChild(td15);
const input15=document.createElement("input");
input15.setAttribute("type","button");
input15.setAttribute("value",".");
input15.setAttribute("onclick","main.value+='.'");
td15.appendChild(input15);
const td16=document.createElement("td");
tr4.appendChild(td16);
const input16=document.createElement("input");
input16.setAttribute("type","button");
input16.setAttribute("value","c");
input16.setAttribute("onclick","main.value=''");
input16.setAttribute("style","background-color:red");
td16.appendChild(input16);
const div5=document.createElement("div");
form.appendChild(div5);
const input17=document.createElement("input");
input17.setAttribute("type","button");
div5.setAttribute("style","margin-top:-95px; display:block");
input17.setAttribute("value","%");
input17.setAttribute("onclick","main.value='%'");
input17.setAttribute("style","margin-left:-223px; margin-top:100px;width:70px");
div5.appendChild(input17);
const div4=document.createElement("div");
div5.appendChild(div4);
const input18=document.createElement("input");
input18.setAttribute("type","button");
div4.setAttribute("style","margin-top:-95px");
input18.setAttribute("value","=");
input18.setAttribute("onclick","main.value=eval(main.value)");
input18.setAttribute("style","margin-left:70px; margin-top:39px;width:210px");
div4.appendChild(input18);

